name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install rubocop
      run: |
        gem install rubocop rubocop-performance rubocop-minitest rubocop-rake
    - name: Lint
      run: rubocop --config=./.rubocop.yml --parallel
