name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3' ]
        gemfile: [ 'Gemfile', 'gemfiles/activerecord_70.gemfile', 'gemfiles/activerecord_71.gemfile', 'gemfiles/activerecord_72.gemfile'  ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install
    - name: Run tests
      run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec rake test:unit
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redisearch: [ '2.8.8' ]
    services:
      redisearch:
        image: redislabs/redisearch:${{ matrix.redisearch }}
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: |
        bundle install
    - name: Run tests
      run: bundle exec rake test:integration
